module Quest_11_input where
import Parser
import Control.Applicative (some, (<|>))
import Data.List (nub)
import Data.Char
import Data.Either

symbol = some (oneOf ['A'..'Z'])
sep0 = char ','
sep1 = char '|'

type Term = (String, [String])

term :: Parser Char Int Term
term = symbol <* (char ':') <~> (sepBy symbol sep0)

final :: Parser Char Int [Term]
final = sepBy term sep1

run part = parse (final >>= (\x -> return (part x)))

example1 = "A:B,C|B:C,A|C:A"
example2 = "A:B,C|B:C,A,A|C:A"

input1 = "I:E,Y|U:E,A|O:U,Y,Y|A:O,E,Y|Y:I,O|E:I,U,O"
input2 = "V:X,C,L,W|S:F,B,X,L|J:M,H,B,H|D:M,Z,W|M:F,V,S,X|W:S,B,N,N|K:W,J,M,X|L:V,C,N|X:B,B,G|G:R,K,T,L|B:T,Q,Z|Z:M,P,P,B|T:Q,B,R|Q:C,M,J|R:H,K,Z,P|P:H,L,L|N:D,Z,S|H:T,S,J|C:R,G,N,R|F:L,L,W"
input3 = "RLZ:KCN,JVF,PLW|MVG:CBC,PCQ,KCN|TPM:HTL,VCL,VCQ|TQP:HTL,TZB,CWH,LWN,TKJ|KNK:RLS,KPM,SWZ|TPL:ZSR,MDM,WJK|JLN:BSL,BKS,HGN|RFL:HGN,KGG,KNK,JLN,WJS|NNJ:LQH,VFW,NXK|ZVV:NNJ,ZQX,JSF|SDT:CBC,LKZ,CZP|MHJ:JLN,TSZ,RDT|DDL:TWN,ZSR,GDH,DDL,WCM|TFM:PLW,TBW,BDZ,KPM,KGB|GKT:TSZ,KNK,BDL,KGG,QZV|FLZ:PGV,TKJ,RRH,TFM,PGV|MRM:BLF,BSL,WHH,HGN,TSZ|VJP:XPL,TSZ,BSL,RDT,FPL|MTJ:PCQ,GDH,WJS,LXN,BLF|LKZ:SWZ,CZP,KPM,NNJ,MVG|ZSR:RKC,VCL,FPL|CBC:QDV,SWZ,CBC,JSF,ZNM|BSL:TZB,MVL,LNS,BKD,NNJ|XPL:LDT,MRM,MVG|MDM:VJM,MHJ,BDL|ZZX:FPL,GCS,TSZ,TKJ,JLN|BLF:ZJQ,MTJ,PGV,ZQL,BKS|QDV:VFW,GDH,WJS|BHP:BKD,CZP,SZC|LWN:GKT,BDZ,HTL,GKT,KCN|PLW:NXK,ZPT,TFM,BHP,JVF|SLV:JLN,RLZ,TZB|WJS:LQH,GJP,FPL,LBW,GKT|ZJQ:QDV,LKZ,ZSR,BHP,KNK|KGB:GJP,ZQX,RLZ|LXN:PCQ,BLF,VCQ|LQH:TZB,ZNM,TQP,TKJ,LNS|HTL:KNK,BDZ,PCQ|WCM:QDV,VFW,ZPT|ZQL:TPL,VCC,MVG|GDH:JVF,GDH,ZZX|SZC:SZC,FLV,CZP,TKJ,ZZX|TWN:XPL,RDT,LDT|RRH:ZPT,BKS,LNS|JVF:BKS,LNS,BHP,LWN,WHH|ZNM:NNJ,BDL,WXC|RKC:WCM,SDT,JVF,RLS,SLV|KPM:TZB,BSL,MVG,SWZ,MTJ|ZQX:VFW,TQP,TPM,MVG,NNJ|RZT:BKS,WSZ,VCQ|BKD:GCS,DRM,PGV|MVL:CBC,VJM,ZNM,BWZ,ZVV|DJN:NXK,TQP,QZV,RDT,ZZX|DRM:SQW,CBC,ZSR|CWH:RZT,LNS,TPL|KGG:HGN,DDL,ZNM,ZSR,NNJ|LBW:TSZ,TSZ,RLZ,DBH,DJN|FPL:FPL,CBC,ZJQ,ZQX,TQP|VJM:RFL,MXV,JSF|DBH:WSZ,RLZ,RFL,VJP,PCQ|PCQ:BDZ,HTL,CWH|VCC:DJN,VJP,ZZX,MVL,TKJ|VGJ:CSB,BKS,WHH|WSZ:QDV,QDV,HGN,LXN,RFL|BKS:WJK,ZQL,BDZ,VCC,VCL|CSB:PCQ,RZT,WJS|VCQ:ZQX,RFL,TKJ,HGN,ZPT|BDZ:RRH,BWZ,MVL,JSF,VGJ|HWL:QZV,GDH,LNS,TWN,JVF|PGV:SDT,MVG,RLZ|RDT:TSZ,MFR,QZV|QZV:MVL,PGV,HWL,HTL,MHJ|WXC:BWZ,MVL,SLV,ZSR,MVL|TKJ:BDL,XPL,GDH|VFW:KGG,BDZ,SDT|SQW:DJN,VCC,ZZX,TBW,SWZ|TTD:JVF,LXN,TTD,VFW,TSZ|WJK:WHH,NNJ,JVF,ZZX,LKZ|MXV:VCL,JSF,BDL|LNS:RLS,MVG,LNS|VCL:ZSR,CSB,RLZ|LDT:BSL,FPL,TPM,PCQ,BKS|RLS:VCC,NXK,SLV,LKZ,GDH|TSZ:KCN,TTD,BKS|NXK:TBW,LKZ,QZV|BDL:FPL,TTD,HGN|BWZ:JSF,TZB,GCS,ZNM,RDT|JSF:DJN,RLZ,ZNM|ZPT:QZV,MDM,PLW,ZSR,WSZ|MFR:TPL,ZQX,JSF|CZP:KGB,WCM,MVG,DBH,RDT|KCN:CWH,TZB,ZNM|SWZ:TPM,TTD,RRH,TZB,GCS|FLV:BKD,TZB,DDL|WHH:SQW,VCQ,FLZ|GCS:VCL,DRM,BWZ|HGN:CZP,TKJ,WJK,MHJ,SDT|GJP:WHH,DDL,HWL|TZB:QDV,TKJ,ZJQ,BLF,BDL|TBW:KGB,VJP,WXC,MTJ,FPL"
